services:
    tuna_cms_node.node_manager:
        class: TunaCMS\Bundle\NodeBundle\NodeManager
        arguments:
            - "%tuna_cms_node.types%"

    tuna_cms_node.request_param_converter.entity_interface_converter:
        class: TunaCMS\Component\Common\Request\ParamConverter\EntityInterfaceConverter
        tags:
            - { name: request.param_converter, priority: 100 }
        arguments:
            - "@doctrine"
            - TunaCMS\Bundle\NodeBundle\Model\NodeInterface
            - "%tuna_cms_node.types.node.model%"

    tuna_cms_node.form.node_type:
        class: TunaCMS\Bundle\NodeBundle\Form\NodeType
        arguments:
            - "%tuna_cms_node.metadata.model%"
        tags:
            - { name: form.type }

    tuna_cms_bundle_node.factory.node_factory:
        class: TunaCMS\Bundle\NodeBundle\Factory\NodeFactory

    tuna_cms_bundle_node.node_extension:
        class: TunaCMS\Bundle\NodeBundle\Twig\NodeExtension
        arguments: ['@tuna_cms_bundle_node.factory.node_factory']
        calls:
            - [initRuntime, ['@twig']]
        tags:
            - { name: twig.extension }

    tuna_cms_bundle_node.form.menu_node_type:
        class: TunaCMS\Bundle\NodeBundle\Form\MenuNodeType
        arguments: ['@tuna_cms_bundle_node.factory.node_factory']
        tags:
            - { name: form.type, alias: TunaCMS\Bundle\NodeBundle\Form\MenuNodeType }
