lexik_translation_edition:
    resource: "@LexikTranslationBundle/Resources/config/routing.yml"
    prefix:   /translation

tuna_file:
    resource: "@TunaCMSFileBundle/Resources/config/routing.yml"

tuna_controllers:
    resource: "@TunaCMSAdminBundle/Controller"
    type:     annotation

