services:
    the_codeine_page.factory:
        class: TheCodeine\PageBundle\Service\PageFactory
        arguments: ["%the_codeine_page.form%", "%the_codeine_page.model%"]

    the_codeine_page.manager:
        class: TheCodeine\PageBundle\Service\PageManager
        arguments: ["%the_codeine_page.model%", "@doctrine.orm.default_entity_manager"]

    the_codeine_page.page_type:
        class: "%the_codeine_page.form%"
        arguments: ["%the_codeine_page.model%"]
        tags:
            - { name: form.type }

    the_codeine_page.param_converter:
        class: TheCodeine\PageBundle\Request\ParamConverter\PageParamConverter
        arguments: ["@the_codeine_page.manager"]
        tags:
            - { name: request.param_converter }

    the_codeine_page.orm_mapped_super_class:
        class: TheCodeine\PageBundle\EventListener\Doctrine\ORMMappedSuperClassSubscriber
        arguments: ["%the_codeine_page.model%"]
        tags:
            - { name: doctrine.event_subscriber, priority: 8192 }

    the_codeine_page.orm_mapped_repository:
        class: TheCodeine\PageBundle\EventListener\Doctrine\ORMRepositoryClassSubscriber
        arguments: ["%the_codeine_page.model%", "%the_codeine_page.repository%"]
        tags:
            - { name: doctrine.event_subscriber, priority: 8192 }