language: php
dist: trusty

php:
    - 5.6

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

env:
    global:
      - ENCRYPTION_LABEL: "384ad717f115"
      - COMMIT_AUTHOR_EMAIL: "office@thecodeine.com"
      - SYMFONY_DEPRECATIONS_HELPER: "weak"

before_script:
    - phpenv config-add travis.php.ini
    - composer update --prefer-source --no-interaction

script:
    - ./run-tests.sh
    - ./run-deploy.sh