services:
    tuna_cms_file.manager.file_manager:
        class: TunaCMS\Bundle\FileBundle\Manager\FileManager
        arguments: ["@filesystem", "%tuna_cms_file.file_manager%"]

    tuna_cms_file.event_listener.file_listener:
        class: TunaCMS\Bundle\FileBundle\EventListener\FileListener
        arguments:
            - "@tuna_cms_file.manager.file_manager"
        tags:
            - { name: doctrine.orm.entity_listener }

    tuna_cms_file.validator_constraints.file_exists_validator:
        class: TunaCMS\Bundle\FileBundle\Validator\Constraints\FileExistsValidator
        arguments: ['@tuna_cms_file.manager.file_manager']
        tags:
            - { name: validator.constraint_validator }

    tuna_cms_file.twig.upload_extension:
        class: TunaCMS\Bundle\FileBundle\Twig\FileExtension
        arguments:
            - "%tuna_cms_file.file_manager%"
            - "@templating.helper.assets"
            - "@liip_imagine.cache.manager"
        tags:
            - { name: twig.extension }
