<?php

namespace TheCodeine\NewsBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use Doctrine\ORM\Query\Expr;


/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
    public function getSimilarCategories($category)
    {
        return $this->getSimilarCategoryIds($category);

    }

    private function getSimilarCategoryIds($category, $categoryIds = array())
    {
        $parent = $category->getParent();
        foreach ($parent->getChildren() as $cat) {
            $categoryIds[] = $cat->getId();
        }

        if ($parent->getParent() == NULL) {
            return $categoryIds;
        } else {
            $this->getSimilarCategoryIds($parent, $categoryIds);
        }
    }
}
