lexik_translation_app:
    resource: "@LexikTranslationBundle/Resources/config/routing/app.yml"

lexik_translation_api:
    resource: "@LexikTranslationBundle/Resources/config/routing/api.yml"
    prefix: /api

lexik_translation_update:
    path:     /translations/{id}
    defaults: { _controller: "TheCodeineTranslationBundle:Rest:update" }
    methods:  [PUT]
