tuna_cms_video:
    manager_class: TunaCMS\Bundle\VideoBundle\Doctrine\VideoManager
    form_type_class: TunaCMS\Bundle\VideoBundle\Form\VideoUrlType
    entity_manager_class: Doctrine\ORM\EntityManager
    twig_extension_class: TunaCMS\Bundle\VideoBundle\Twig\Extension\VideoPlayerExtension
